### ISSUE TITLE
请问现在还能用吗？

### ISSUE THREAD

**Issue by qianzui** [huangdiv/user-scripts#1]
我这边一直用不了，换了两个浏览器都一样

**Comment by huangdiv** [comment]
这个脚本是写来个人自用的，由于测试脚本需要河南专技在线的账号，而我的账号课程已经学完了，无法测试现在脚本能不能用。如果实在想让我帮忙看看，可在QQ上私发给我你的账号和密码，我抽时间改改脚本。账号密码涉及您的隐私，介意的话就算了。
