### ISSUE TITLE
[已停更]脚本失效在这里反馈。

### ISSUE THREAD

**Issue by AshiakerWang** [huangdiv/user-scripts#2]
### 最新版本：

**小伙伴们，终于抽出时间更新了一下，现在完美适配2021公需课和专业课，更新到最新版本应该可以一次性刷完所有课程了，快来试试吧。**

**目前最新是[3.2版本](https://greasyfork.org/zh-CN/scripts/389705-%E6%B2%B3%E5%8D%97%E4%B8%93%E6%8A%80%E5%9C%A8%E7%BA%BF%E8%BE%85%E5%8A%A9)。**

**Comment by huangdiv** [comment]
可否具体一点，比如留下：
1.你的课程视频学习页面的网址;
2.浏览器右上角点击插件管理器，提交本插件生效的截图；
3. 视频学习页面按F12到console页面，提交里面的文字或者截图。

**Comment by AshiakerWang** [comment]
您好，非常感谢您的回复。

１.　网址为：http://hnzj.user.ghlearning.com/learning/index?myClassId=72e651df-c9c2-4686-b3a8-37cda2e6ccca（需要账号和密码登录）
２.　插件开启的截图如下：
![image](https://user-images.githubusercontent.com/14258909/81250920-b82f9480-9054-11ea-8e96-76c414082a57.png)
３.　F12的concole页面截图:
![image](https://user-images.githubusercontent.com/14258909/81251237-5b80a980-9055-11ea-9a9b-12b34061acee.png)

文字内容:
2index:15 GET http://hnzj.user.ghlearning.com/common/components/play/js/player.js net::ERR_ABORTED 404 (Not Found)
DevTools failed to load SourceMap: Could not load content for http://hnzj.user.ghlearning.com/static/es5-shim.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
2index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1 A parser-blocking, cross site (i.e. different eTLD+1) script, http://res.wx.qq.com/connect/zh_CN/htmledition/js/wxLogin.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
(anonymous) @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
u @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
(anonymous) @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
(anonymous) @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
u @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
(anonymous) @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
(anonymous) @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
u @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
(anonymous) @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
(anonymous) @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
u @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
window.webpackJsonp @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
(anonymous) @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
DevTools failed to load SourceMap: Could not load content for chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/jquery.min.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
_library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
ajax @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
kt.<computed> @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
getPlayerSafeToken @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
playVideoConfigAdapt @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
getH5VideoPlayer @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
playVideo @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
playVideo @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
playVideo @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
play @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
(anonymous) @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
dispatch @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
m.handle @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
trigger @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
(anonymous) @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
each @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
each @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
trigger @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
selectVideo @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
(anonymous) @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
readJsonForVar @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
(anonymous) @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
u @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
fireWith @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
l @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
u @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
XMLHttpRequest.send (async)
send @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
ajax @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
kt.<computed> @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
myClass @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
init @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
(anonymous) @ index-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
u @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
fireWith @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
ready @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1
O @ _library-b6fe7c6793cee9891980.js?b6fe7c6793cee9891980:1

另: 浏览器为Chrome(verision: 81.0.4044.138)。

**Comment by huangdiv** [comment]
网站是支持的，但是明显脚本没有生效，如果生效的播放页面，F5刷新页面会给提示，如下图：
![image](https://user-images.githubusercontent.com/55480312/81278729-a5cf4e00-9088-11ea-97b5-3f1a1aa6d5f1.png)
你的播放器页面刷新有这样的弹窗提示么？

**Comment by huangdiv** [comment]
看你的console页面截图，可能是jQuery没有加载成功导致的。如果是，这个问题我暂时还不了解什么原因，待查。

**Comment by AshiakerWang** [comment]
> 网站是支持的，但是明显脚本没有生效，如果生效的播放页面，F5刷新页面会给提示，如下图：
> ![image](https://user-images.githubusercontent.com/55480312/81278729-a5cf4e00-9088-11ea-97b5-3f1a1aa6d5f1.png)
> 你的播放器页面刷新有这样的弹窗提示么？

大佬您好，我的没有这个提示。

**Comment by aqing-git** [comment]
确实是用不了了。网站代码像是改过了。情况和AshiakerWang提到的一样。不提示弹窗。大佬有空看下。

**Comment by huangdiv** [comment]
我这里测试，脚本运行依旧是正常的。

由于地域和课程不同，播放器的设置和功能可能有些差别，而本脚本的正常运行，依赖播放器页面提供的js接口，因此我无法一一测试。

如果非常需要我提供帮助，可以在课程正常播放的页面按下F12，进入console页面，手动输入`window.s2j`，然后应该会弹出一些接口功能提示如下图：
![image](https://user-images.githubusercontent.com/55480312/81517974-233bdc80-936f-11ea-8df6-abe9389993a9.png)

上面的截图是我这里的播放器提供的接口，请在回复中提交你的播放器console页面的这个红框区域的截图，我好尝试改进脚本。

**Comment by aqing-git** [comment]
脚本可以正常弹窗了，答题框弹出后，进度不会增加。


![异常](https://user-images.githubusercontent.com/65142863/81519735-ce9b6000-9374-11ea-87d0-f7a20421f923.png)

**Comment by cvuuhk** [comment]
大佬你好。
网址链接：http://hnzj.user.ghlearning.com/learning/index?myClassId=4693b40d-840f-446e-a517-eb59202b8356
![image](https://user-images.githubusercontent.com/36870468/81951339-a1320900-9637-11ea-886c-43f6f80a1b41.png)
已经没有 `s2j_onPlayerInitOver` 变量了

**Comment by huangdiv** [comment]
1.6版本已更新，请大家试用，有问题可在下面提出。

**Comment by huangdiv** [comment]
> 大佬你好。
> 网址链接：http://hnzj.user.ghlearning.com/learning/index?myClassId=4693b40d-840f-446e-a517-eb59202b8356
> ![image](https://user-images.githubusercontent.com/36870468/81951339-a1320900-9637-11ea-886c-43f6f80a1b41.png)
> 已经没有 `s2j_onPlayerInitOver` 变量了

如果发现没有 `s2j_onPlayerInitOver` 变量，本脚本暂不支持该播放器。

**Comment by huangdiv** [comment]
1.9版发布，支持自动进入未完成的课程，学完一个课程返回课程列表自动学习下一个未完成的课程。

**Comment by huangdiv** [comment]
经历这两天连续的几次迭代升级，本脚本功能已经比较完善。亲测支持河南专技在线的公需科目，以此为基础搭建的地市区县的专业科目这两个内容的自动学习，只需提前登录，购买班级，选好课程，进入课程列表即可。

目前已知问题：
- 若某些地区播放器不支持`window.s2j_onPlayerInitOver`等接口调用的，本脚本无效；
- 从付款界面直接进入课程学习的，无法自动进行课程选择，建议从已选课程列表进入课程学习。

若发现其他问题，请在[脚本反馈区](https://greasyfork.org/zh-CN/scripts/389705-%E6%B2%B3%E5%8D%97%E4%B8%93%E6%8A%80%E5%9C%A8%E7%BA%BF%E8%BE%85%E5%8A%A9/feedback)，[GitHub](https://github.com/huangdiv/user-scripts/issues/2)或者[个人博客页](https://huangdiv.com/tech/ghlearning-assist/)反馈。

**Comment by ppz123** [comment]
大佬你好，今天是2020/10/18，你8月份发的那个脚本不能使用，进网页还是会有声音，大替还是会弹出，而且有的时候也无法自动跳转。麻烦您有空看一下。

**Comment by huangdiv** [comment]
> 大佬你好，今天是2020/10/18，你8月份发的那个脚本不能使用，进网页还是会有声音，大替还是会弹出，而且有的时候也无法自动跳转。麻烦您有空看一下。

麻烦提供一下播放页面的网址

**Comment by ppz123** [comment]
感谢大佬回复
这个是课程的页面http://hnzj.user.ghlearning.com/my/play_study?myLearnTaskId=8847d0fe-b3f8-4e41-a56a-c39482a18a6f
这个是我点了一个课程播放的页面http://hnzj.user.ghlearning.com/learning/index?myClassId=4700c1e8-43f5-4812-9497-e60680992ccf




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huangdiv/user-scripts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月18日(星期天) 上午10:56
收件人:&nbsp;"huangdiv/user-scripts"<user-scripts@noreply.github.com&gt;;
抄送:&nbsp;"On the way"<1427275397@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [huangdiv/user-scripts] 脚本失效在这里反馈。 (#2)





  
大佬你好，今天是2020/10/18，你8月份发的那个脚本不能使用，进网页还是会有声音，大替还是会弹出，而且有的时候也无法自动跳转。麻烦您有空看一下。
  
麻烦提供一下播放页面的网址

**Comment by kfsgxey** [comment]
大佬您好，2021年的河南专技课程每单元测试都会停止，一个完整课程学完后不能自动回到课程列表，希望能够更新一下

**Comment by huyan9968** [comment]
![image](https://user-images.githubusercontent.com/82623790/115951792-45455500-a515-11eb-8219-4371c78e9ee0.png)

**Comment by huyan9968** [comment]
![image](https://user-images.githubusercontent.com/82623790/115952442-80955300-a518-11eb-91f9-db33a2d22bc1.png)
你好兄弟，答题页面还得手动操作。

**Comment by huangdiv** [comment]
小伙伴们，终于抽出时间更新了一下，更新到最新的2.4版本应该可以一次性刷完所有课程了，快来试试吧。

**Comment by Originsin** [comment]
现在更新到2.0了，大佬还更新脚本不了？

**Comment by zhangyiyifan** [comment]
河南专技在线3.6版本，时间久了无法保存进度，视频播完进度还是在20%左右

**Comment by YangtseSu** [comment]
http://hnsl.user.ghlearning.com/
没办法自动开始。

**Comment by huangdiv** [comment]
由于本人继续教育不再使用河南专技在线，本脚本停止维护与更新。
