### ISSUE TITLE
2021年课程问题

### ISSUE THREAD

**Issue by ohahay** [huangdiv/user-scripts#4]
https://hnzj.user.ghlearning.com/learning
2021年课程不能自动下一课，
新增刷脸功能，
已测试的内容
1、刷脸二维码 是个摆设
转向网址所有课程是同一个二维码，同一个网址，
随便上传一个图片就能验证成功。
2、单元测试会自动完成。
只点 视频课程，一个课程学完，单元测试会自动完成。

**Comment by huangdiv** [comment]
适配2021课程的脚本已更新，请更新脚本到最新版使用。 #2
