### ISSUE TITLE
会出现视频进度和刷课进度不匹配的情况

### ISSUE THREAD

**Issue by cx99325** [huangdiv/user-scripts#7]
作者大佬您好，我看河南专技在线脚本反馈也有人提出，这种视频播放大半进度只有小半的情况。
目前使用脚本会出现：_课时内视频播放完成，但是课时进度只有一半多一些，需要重复手动点击以往视频重刷_。（也许是网站播放自身的问题）
建议加入定时刷新浏览器界面的操作，用于同步最新的播放进度和课时进度。

**Comment by GSCong** [comment]
向https://hnzj.user.ghlearning.com/train/cms/my-video/cv.gson提交请求返回
{"respCode":200,"respDesc":"","attribute":{"data":{"respCode":"OVER_TIME","respDesc":"视频计时超时，请重新播放","myClassId":null,"classId":null,"courseId":null,"videoId":null,"classLearnRate":0.0,"courseLearnRate":0.0,"videoLearnRate":0.0,"gotRequiredHours":0.0,"gotElectiveHours":0.0}}}
然后进度就不变了，这时候得刷新页面
